language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - python -m pytest --cov=autostack --cov-report=xml --pep8 --pylint autostack/
after_success:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT